backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "pages"
    label: "頁面內容"
    files:
      - file: "index.html"
        label: "首頁"
        name: "home"
        fields:
          - {label: "標題", name: "title", widget: "string"}
          - {label: "內容", name: "body", widget: "markdown"}
